default_stages: [commit]
repos:
  - repo: https://github.com/ambv/black
    rev: master
    hooks:
      - id: black
#        args: [--line-length=120,  --target-version=py36, --safe]
        args: [--line-length=120,  --skip-string-normalization, --safe]
        language_version: python3.6
        verbose: true
        exclude: (\.idea|^blueapps/|^blueking/|^pipeline/|^flower/|^wiki|^iam/)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: flake8
        entry: flake8 --config ./.flake8
  - repo: local
    hooks:
        - id: check-coverage
          name: check coverage
          entry: bash test_script/check.sh
          language: system
